version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      MYSQL_DSN: wabot_user:password@tcp(mysql:3306)/wabot_db?parseTime=true
      WA_BUSINESS_ACCOUNT_ID: ''
      WA_ACCESS_TOKEN: ''
      WA_BASE_URL: https://graph.facebook.com/v20.0
      WA_SECRET: ''
      FINPAY_BASE_URL: ''
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wabot_db
      MYSQL_USER: wabot_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
